# Generated by Django 2.0 on 2020-03-25 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='类别名')),
                ('code', models.CharField(default='', max_length=100, verbose_name='类别code')),
                ('desc', models.CharField(default='', max_length=100, verbose_name='类别描述')),
                ('category_type', models.IntegerField(choices=[(1, '一级类别'), (2, '二级类别'), (3, '三级类别'), (4, '四级类别')], verbose_name='所属分类')),
                ('is_tab', models.BooleanField(default=False, verbose_name='是否导航')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo2.Types', verbose_name='父级类别')),
            ],
            options={
                'verbose_name': '类别表',
                'verbose_name_plural': '类别表',
            },
        ),
    ]
